### ISSUE TITLE
skimage 0.17+ does not load tiff files properly

### ISSUE THREAD

**Issue by ulisrael** [vanvalenlab/deepcell-tf#511] opened 2021-04-16 00:23 UTC
skimage 0.17.1 vs skimage 0.16.1

in skimage 0.17 they removed skimage.external 
- I was using from skimage.external.tifffile.TiffFile to load images
- when I tried to use skimage.io.imread to load the same images it doesn't work. I even tried using it with the plugin specified

should we fix deepcell to version 0.16.1 ?

**Comment by willgraf** [comment] 2021-05-04 00:56
We should definitely NOT fix `skimage` to 0.16.1 since there are patches to 0.16.x that we would not be able to use. Additionally, `skimage` 0.16.x is already a few major releases behind. 

Could you please elaborate on how loading the images didn't work? What did you expect to happen vs what did happen?

**Comment by willgraf** [comment] 2021-06-16 22:20
I think the issue is that `skimage.io.imread` automatically converts images to channels last, which may have disrupted your pipeline.

```python
import numpy as np
import tifffile
from skimage.io import imread

img_path = 'test-file.tif'

x = imread(img_path)
y = tifffile.imread(img_path)

# skimage.io.imread always loads as channels-last
# tiffile.imread does not, test file is channels-first
z = np.rollaxis(y, 0, 3)

np.array_equal(x, z)  # True!
```

Using:

```
tifffile==2020.6.3
scikit-image==0.18.1
```

**Comment by willgraf** [comment] 2021-06-21 19:47
Closing this issue as resolved - the difference between `tifffile` and `skimage.io` is that the latter always returns channels last.

**Closed by willgraf** 2021-06-21 19:47 UTC
Labels: bug
