### ISSUE TITLE
ValueError when running 3D Watershed 

### ISSUE THREAD

**Issue by aziabari** [vanvalenlab/deepcell-tf#249] opened 2019-10-23 14:48 UTC
Hi,

I am running **3D Watershed - Fully Convolutional.ipynb** and get the following error when run the code:

**ValueError: Cannot feed value of shape (3, 61, 61, 3, 1) for Tensor 'image_normalization3d_14/Placeholder:0', which has shape '(15, 61, 61, 3, 1)'**

I trained the model, saved it, and when I try to run the model (as follows),  it doesn't like to accept an input shape that is different from training (which is weird!)

**run_fgbg_model = model_zoo.bn_feature_net_skip_3D(receptive_field=receptive_field,
    n_features=2,
    n_frames=frames_per_batch,
    n_skips=n_skips,
    n_conv_filters=32,
    n_dense_filters=128,
    input_shape=tuple(X_test.shape[1:]),
    multires=False,
    last_only=False,
    norm_method=norm_method)
run_fgbg_model.load_weights(fgbg_weights_file)**

**Comment by willgraf** [comment] 2019-10-23 23:03
It looks like this is a bug caused by https://github.com/vanvalenlab/deepcell-tf/blob/dfb7e682a4b05d59a88ac3ca2127f9dd76a99888/deepcell/layers/normalization.py#L107-L114.  By setting `self.kernel = W` directly and not calling `self.add_weight`, we can prevent any weights from being affected by the different input shape.

I'm testing this out in PR #250

**Comment by aziabari** [comment] 2019-10-24 01:41
Thank you for your reply.

In the code you mentioned, W is defined after self.kernel. 
Should we move self.kernel to after that and set it equal to W?

**Comment by willgraf** [comment] 2019-10-24 16:47
This issue is resolved by #250 

Yes, the issue can be fixed by setting `self.kernel = W` instead of calling `add_weight()`, which is how the PR fixes it.  Tests pass and both 2D and 3D notebooks train successfully.

This fix will be released in the `0.3.1` release (maybe early next week), but will be availbale in the master shortly.

**Comment by aziabari** [comment] 2019-10-24 16:57
Great. Thank you very much.

**Comment by aziabari** [comment] 2019-12-16 16:54
**I just tested your updated code and the problem still persists.
My training data are 128x128x128.
I have used frames_per_batch=3

I have 4 test volumes (X_test.shape = (4, 128, 128, 128, 1))
When I want to load the model for testing I ran the following code,**

run_fgbg_model = model_zoo.bn_feature_net_skip_3D(
    receptive_field=receptive_field,
    n_features=2,
    n_frames=frames_per_batch,
    n_skips=n_skips,
    n_conv_filters=32,
    n_dense_filters=128,
    input_shape=tuple(X_test.shape[1:]),
    multires=False,
    last_only=False,
    norm_method=norm_method)
run_fgbg_model.load_weights(fgbg_weights_file)

**And I get the following error:**

ValueError: Cannot feed value of shape (3, 29, 29, 1, 1) for Tensor 'image_normalization3d_25/Placeholder:0', which has shape '(128, 29, 29, 1, 1)

**Comment by willgraf** [comment] 2019-12-17 19:12
Are you sure you are using the non-weighted image normalization layer?

If the error is happening during `run_fgbg_model.load_weights`, it looks like the image norm layer is in fact loading weights (since its the layer causing the error).

**Comment by aziabari** [comment] 2019-12-17 20:17
I am not clear  what you mean. We are running the model. The model is trained on only a frame_pe_batch at a time, therefore a new model is  instantiated, which will load the trained weights.

According to part 11 in: https://github.com/vanvalenlab/deepcell-tf/blob/master/scripts/watershed/Watershed%20Transform%203D%20Fully%20Convolutional.ipynb

we don't need to change anything expect the input shape.
The input shape is different than frame_per_batch used in training, and that is producing error!

I am not sure where should I make changes to use non-weighted image normalization layer?!

Thanks for your help in advance.

**Comment by willgraf** [comment] 2019-12-17 20:23
In part 11 the model is created, and then the weights are loaded using `run_fgbg_model.load_weights(fgbg_weights_file)`.  

The error looks like it is coming from the ImageNormalization layer (one of the very first layers of the model):

```
ValueError: Cannot feed value of shape (3, 29, 29, 1, 1) for Tensor 'image_normalization3d_25/Placeholder:0', which has shape '(128, 29, 29, 1, 1)
```

With #250, the image normalization layer should not have any weights, and should NOT throw an error during `load_weights`. You should not need to make any code changes if you are using code after the fix. Can you please confirm you are using the newest version of deepcell?

**Comment by aziabari** [comment] 2019-12-19 16:36
I was using the previous version (before you made changes to the code) and I did change the normalization.py myself according to the previous suggestions you made.

To avoid confusion, I deleted everything, pulled the latest git version of the code,  and ran the following:

git clone https://github.com/vanvalenlab/deepcell-tf.git
cd deepcell-tf
docker build -t $USER/deepcell-tf 

I also made sure all the requirements are current.


However, the code even doesn't work with the example you provided for 3D watershed on mousebrain. The training works fine but when I try testing the code I get the following error during load_weights step!
It seems the exist still an issue.



ValueError                                Traceback (most recent call last)
<ipython-input-15-806636d385b4> in <module>
     10     last_only=False,
     11     norm_method=norm_method)
---> 12 run_fgbg_model.load_weights(fgbg_weights_file)

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name)
    160         raise ValueError('Load weights is not yet supported with TPUStrategy '
    161                          'with steps_per_run greater than 1.')
--> 162     return super(Model, self).load_weights(filepath, by_name)
    163 
    164   @trackable.no_automatic_dependency_tracking

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in load_weights(self, filepath, by_name)
   1422         saving.load_weights_from_hdf5_group_by_name(f, self.layers)
   1423       else:
-> 1424         saving.load_weights_from_hdf5_group(f, self.layers)
   1425 
   1426   def _updated_config(self):

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    747     symbolic_weights = _legacy_weights(layer)
    748     weight_values = preprocess_weights_for_loading(
--> 749         layer, weight_values, original_keras_version, original_backend)
    750     if len(weight_values) != len(symbolic_weights):
    751       raise ValueError('Layer #' + str(k) + ' (named "' + layer.name +

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend)
    372     weights = convert_nested_time_distributed(weights)
    373   elif layer.__class__.__name__ in ['Model', 'Sequential']:
--> 374     weights = convert_nested_model(weights)
    375 
    376   if original_keras_version == '1':

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in convert_nested_model(weights)
    348             weights=weights[:num_weights],
    349             original_keras_version=original_keras_version,
--> 350             original_backend=original_backend))
    351         weights = weights[num_weights:]
    352 

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend)
    454         weights[1] = conv_utils.convert_kernel(weights[1])
    455     if K.int_shape(layer.weights[0]) != weights[0].shape:
--> 456       weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
    457       if layer.__class__.__name__ == 'ConvLSTM2D':
    458         weights[1] = np.transpose(weights[1], (3, 2, 0, 1))

<__array_function__ internals> in transpose(*args, **kwargs)

~usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in transpose(a, axes)
    648 
    649     """
--> 650     return _wrapfunc(a, 'transpose', axes)
    651 
    652 

~usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: axes don't match array

**Comment by aziabari** [comment] 2019-12-19 16:58
By the way, here is what I get for model summary. The warning at the end was not there before.
Not sure if that is causing the issue!

fgbg_model.summary()                                                                                                                                                      
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 3, 128, 128, 0                                            
__________________________________________________________________________________________________
image_normalization3d (ImageNor (None, 3, 128, 128,  2523        input_1[0][0]                    
__________________________________________________________________________________________________
model (Model)                   (None, 3, 128, 128,  164573      image_normalization3d[0][0]      
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 3, 128, 128,  0           image_normalization3d[0][0]      
                                                                 model[1][0]                      
__________________________________________________________________________________________________
model_1 (Model)                 (None, 3, 128, 128,  170643      concatenate[0][0]                
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 3, 128, 128,  0           image_normalization3d[0][0]      
                                                                 model_1[1][0]                    
__________________________________________________________________________________________________
model_2 (Model)                 (None, 3, 128, 128,  170643      concatenate_1[0][0]              
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, 3, 128, 128,  0           image_normalization3d[0][0]      
                                                                 model_2[1][0]                    
__________________________________________________________________________________________________
model_3 (Model)                 (None, 3, 128, 128,  170643      concatenate_2[0][0]              
==================================================================================================
WARNING:tensorflow:Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
Total params: 1,326,201
Trainable params: 647,176
Non-trainable params: 679,025
__________________________________________________________________________________________________

**Comment by willgraf** [comment] 2019-12-19 18:52
I can confirm this is an issue in the master branch. Master branch is under development and may change from day to day.

Please use the `vanvalenlab/deepcell-tf:0.4.0-gpu` docker image, which currently supports the 3D models.

**Comment by willgraf** [comment] 2019-12-19 19:55
I'm closing this issue as the original issue was indeed fixed, but there is a NEW problem in master, tracked by #285

**Closed by willgraf** 2019-12-19 19:55 UTC
