### ISSUE TITLE
Support for Python 3.11 onward

### ISSUE THREAD

**Issue by ChannyClaus** [vanvalenlab/deepcell-tf#713] opened 2024-03-14 12:52 UTC
**Is your feature request related to a problem? Please describe.**
We are in the process of updating the Python version to 3.12 and noticed DeepCell does not support Python versions past 3.10.

**Describe the solution you'd like**
It would be ideal if it can support Python 3.11 onwards.

**Describe alternatives you've considered**
It is not the end of the world for us to continue to run DeepCell in Python3.8 docker image, but for consistency (we are moving to Python 3.12 for everything else 🥲 ) it would be lovely if we can do the same for DeepCell.

**Comment by rossbar** [comment] 2024-03-14 16:43
I will close this as duplicate of #711 - see the description there for further detail.

As always, contributions related to updating the framework and evaluating the re-trained model are more than welcome!

**Closed by rossbar** 2024-03-14 16:43 UTC
Labels: enhancement

**Comment by ChannyClaus** [comment] 2024-03-14 17:45
ah oops my bad, should've looked before posting 😭 - it's like right there
