### ISSUE TITLE
include README references to other repos and website

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/deepcell-tf#104] opened 2018-10-31 22:44 UTC

**Comment by willgraf** [comment] 2018-12-19 17:06
Looks like a duplicate of #74 
Maybe we can close this and track it in that issue.

**Comment by willgraf** [comment] 2019-01-10 22:30
Is this issue resolved?

@MekWarrior added links to readthedocs for deepcell and the kiosk, as well as a link to the lab website.

**Closed** 2019-01-10 22:37 UTC
